name: spiderweb
base: core22
version: '0.1'
summary: Universal Code Debugger CLI - Multi-language static analysis tool
description: |
  Spiderweb is a lightweight, regex-based static analysis tool that instantly shows:
  - Callers: Which functions call a target function
  - Callees: Which functions are called by a target function
  - Both: Complete call relationship tree

  Supported Languages:
  - Python (.py, .pyi)
  - JavaScript/TypeScript (.js, .jsx, .ts, .tsx, .mjs, .cjs)
  - Nim (.nim, .nims, .nimble)
  - Rust (.rs)
  - C/C++ (.c, .cpp, .cc, .cxx, .h, .hpp, .hxx)

  Usage:
    spiderweb file:function --show=callers|callees|both

  Examples:
    spiderweb test.py:greet --show=callers
    spiderweb test.nim:greet --show=callees
    spiderweb main.rs:main --show=both

grade: stable
confinement: strict

apps:
  spiderweb:
    command: bin/spiderweb
    plugs:
      - home

parts:
  spiderweb:
    plugin: nil
    source: .
    build-packages:
      - curl
      - xz-utils
    override-build: |
      set -eux

      # Install Nim locally inside the build environment
      mkdir -p nim
      cd nim
      curl -L -o nim.tar.xz https://nim-lang.org/download/nim-2.0.0-linux_x64.tar.xz
      tar xf nim.tar.xz
      export PATH=$PWD/nim-2.0.0/bin:$PATH

      # Install Nim dependencies
      cd $SNAPCRAFT_PROJECT_DIR
      nimble install -y cligen

      # Build spiderweb
      nim c -d:release --opt:speed \
        -o:$SNAPCRAFT_PART_INSTALL/bin/spiderweb \
        src/spiderweb.nim
