name: spiderweb
base: core22
version: '0.1'
summary: Universal Code Debugger CLI for Nim codebases
description: |
  Spiderweb is a static analysis tool that shows function call relationships
  in Nim codebases. It can display callers (who calls this function) and
  callees (what this function calls) in both ASCII tree and JSON format.

  Usage:
    spiderweb file:function --show=callers|callees|both

  Examples:
    spiderweb test.nim:greet --show=callers
    spiderweb src/main.nim:init --show=both

grade: stable
confinement: strict

apps:
  spiderweb:
    command: bin/spiderweb
    plugs:
      - home

parts:
  spiderweb:
    plugin: nil
    source: .
    build-packages:
      - curl
      - xz-utils
    override-build: |
      set -eux

      # Install Nim locally inside the build environment
      mkdir -p nim
      cd nim
      curl -L -o nim.tar.xz https://nim-lang.org/download/nim-2.0.0-linux_x64.tar.xz
      tar xf nim.tar.xz
      export PATH=$PWD/nim-2.0.0/bin:$PATH

      # Install Nim dependencies
      cd $SNAPCRAFT_PROJECT_DIR
      nimble install -y cligen

      # Build spiderweb
      nim c -d:release --opt:speed \
        -o:$SNAPCRAFT_PART_INSTALL/bin/spiderweb \
        src/spiderweb.nim
